### ISSUE TITLE
Add Netlify deployment of Ladle

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/react-components#12]
Would be great to have the latest ~~Storybook~~ Ladle deployed, but also to have deploy previews of pull requests so reviewers can easily try out the changes.

**Comment by davidjgoss** [comment]
@mattwynne @aslakhellesoy is there a netlify account we can use to set this up? We use it for the docs site too, right?

**Comment by aurelien-reeves** [comment]
I think Netlify would be "too much" for simply hosting storybook.
I am pretty sure we could do something using github actions and github pages.

To answer your question: yes, we have a Netlify account for the documentation website, so if you really want to use Netlify, we can set that up ;)

**Comment by aurelien-reeves** [comment]
Oh, you were interesting in the "review" thing!
Indeed, I don't know such possibilities yet with github pages

**Comment by davidjgoss** [comment]
@mattwynne we discussed Netlify a bit the other day in the context of websites - would you mind adding me to the relevant Cucumber team so I can set this up? GitHub email address is the one.

**Comment by mattwynne** [comment]
@davidjgoss unfortunately I don't have privileges in the SmartBear Netlify org to do that. I'll pinged @declark who does to ask him if he can help.

**Comment by declark** [comment]
@mattwynne and @davidjgoss of course I can help! Please send me what you need, and I'll take care of it.

**Comment by mattwynne** [comment]
Thanks @declark - I just sent you an email with the details.

**Comment by davidjgoss** [comment]
This is set up now, thanks all.

it will need https://github.com/cucumber/react-components/pull/337 in order to deploy successfully, working on that now.
