### ISSUE TITLE
Regression: Filter-by seems to not pull through only cases matching filter type.

### ISSUE THREAD

**Issue by luke-hill** [cucumber/react-components#136]
Previously in cucumber 5.3 -> cucumber-html-formatter 9 this functionality worked
Currently in cucumber 7 -> cucumber-html-formatter 16 this functionality is no longer working

**Describe the bug**
Filter-by passed seems to pull in additional test cases

**To Reproduce**
I have a report that has the following
 passed	128 scenarios
 skipped	24 scenarios
 unknown	59 scenarios

**Expected behavior**
Filtering works returns only the ones checked

**Screenshots**
Can pair and show video

**Desktop (please complete the following information):**
```
Implementation	cucumber-ruby - 7.0.0
Runtime	ruby - 2.7.3
OS	linux - cucumber/cucumber-react#1 SMP Tue Jun 15 20:57:50 UTC 2021
CPU	x86_64
```

**Additional context**
In console we get one warning
```
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
```

**Comment by mpkorstanje** [comment]
Indeed, search is implemented in the react app.

Here specifically for any one who wants to take a look:

https://github.com/cucumber/cucumber-react/blob/main/src/search/Search.ts

**Comment by pk** [comment]
I've looked into the source code and more specifically to the specs for the tag search and those specs are quite convincing, in terms of what they test and if they pass it should be working...

HOWEVER:
It seems that the filters and search are very much confused with the Features which use the **Rule** keyword. When I effectively tell the report not to show any issues (unticking all the filters) what is left are the Features with the **Rule** in them.

Search for Features without the **Rule** keyword seems to work as expected, it's just that the Features with **Rule** are always mixed in to the results.

I think that changing the test suite fixture to the following would reveal the problems.
`
@system
Feature: Solar System
  @star
  Scenario: Sun
    Given is the center of galaxy

  Rule: Our Galaxy
    @planet
    Scenario: Earth
      Given is the sixth planet from the Sun

    @dwarf
    Scenario: Pluto
      Given it is not really a planet
`

This fixture would produce report where the feature would be visible all the time regardless of the Filters.

I'll verify this by trying to run the test suite later.
