### ISSUE TITLE
Minor UI issue on search box

### ISSUE THREAD

**Issue by luke-hill** [cucumber/react-components#218]
### 👓 What did you see?

**![image](https://user-images.githubusercontent.com/20105237/174274065-ee7c6239-6067-4b1b-9317-ecea935ac88b.png)**

### ✅ What did you expect to see?

Something similar to my red pen here

![image](https://user-images.githubusercontent.com/20105237/174274205-a11e4aea-901b-48cd-ba9d-62bb465718bd.png)

Black outline occurs when you click once in the text box - But you have to "guess" where the text box is.

### 📦 Which tool/library version are you using?

cucumber-ruby 8.0.0

### 🔬 How could we reproduce it?

Run any scenario generating a report in cucumber ruby 8.0.0

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by ludeknovy** [comment]
Hello, would something like that be acceptable ?
<img width="549" alt="Screenshot 2022-08-17 at 10 50 51" src="https://user-images.githubusercontent.com/13610612/185076836-0d73363b-d334-4df1-878e-dcf4bb756fd7.png">

**Comment by luke-hill** [comment]
I mean each to their own. Whoever picks this up and wants to improve it can do. I'd personally have it a bit thicker but I'm not a very good JS'er. It definitely solves the problem

If you're able to fix it, push up a PR and someone from the team will look at it.
