### ISSUE TITLE
Markdown rendering of description can be surprising

### ISSUE THREAD

**Issue by mattwynne** [cucumber/react-components#225]
### 🤔 What's the problem you're trying to solve?

See [this comment](https://github.com/cucumber/common/issues/1929#issuecomment-1164345543)

People are surprised when deliberate newlines disappear when their features are rendered.

### ✨ What's your proposed solution?

I suggest adding a `title` element somewhere that contains the original raw text from the `description` field so there's a bit more transparency about what's happening.

### ⛏ Have you considered any alternatives or workarounds?

We *could* also add some kind of option to toggle markdown rendering (and if markdown's disabled, just use a fixed-width font for the description)

### 📚 Any additional context?

https://cucumber.io/blog/bdd/user-stories-and-bdd-features-are-not-stories/ 😉

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by luke-hill** [comment]
Looking at the raw source which is present inside the html, the original quantity of newlines is present, but it's one huge data-chunk, as opposed to split up ones. The full raw text from the .feature file is present in this stream.

A partial example is

```
{"line":53}}}},
{"source":{"uri":"features/foo/bar/baz.feature","data":"Feature: Forgot Password\n\n  As an existing customer\n  I want to be able to reset my password if I have forgotten it\n  So that I can continue to use the thing\n\n  This requires a foobarbaz\n  They then must subsequently do a barbazbay\n\n  Scenario: 
```

**Comment by davidjgoss** [comment]
> We could also add some kind of option to toggle markdown rendering

FWIW, I think we are slowly rolling towards having some kind of options mechanism for the HTML formatter. There's stuff like https://github.com/cucumber/react-components/issues/181 and also theming - nothing has yet been compelling enough on its own, but maybe collectively it's worth a look.

> (and if markdown's disabled, just use a fixed-width font for the description)

Minor point, but rather than a monospace font I think we'd just use the regular font and `white-space: pre-wrap` in order to preserve the original spacing.

**Comment by mattwynne** [comment]
Interestingly, these comment blocks in Github (which I assume use [GFM](https://github.github.com/gfm/)) do preserve newlines:

First line
Second line

Which comes out as:
```
<p>First line<br>Second line</p>
```

That doesn't match my reading of [the spec](https://github.github.com/gfm/#soft-line-breaks). I wonder what's going on?

**Comment by mattwynne** [comment]
🎉 thanks @davidjgoss!
