### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by mattwynne** [cucumber/react-components#34]
## What's the problem you've observed? 🤔

The name of this repo follows the naming pattern of other full Cucumber implementations (Cucumber-Ruby, Cucumber-JVM etc.) which suggests to the uninitiated that this might be a flavour of Cucumber designed for testing React apps. It's nothing like that.

## Do you have a proposal for making it better? 🦄

I suggest we rename it to `cucumber/react-components`

**Comment by aurelien-reeves** [comment]
Agreed

**Comment by aslakhellesoy** [comment]
If we do that, I think we should consider renaming the npm module accordingly (and deprecate the old one)

**Comment by davidjgoss** [comment]
This is done now https://www.npmjs.com/package/@cucumber/react

**Comment by mattwynne** [comment]
❤️
