### ISSUE TITLE
Attachments added in examples aren't shown

### ISSUE THREAD

**Issue by badeball** [cucumber/react-components#356]
### 👓 What did you see?

A HTML report with one attachment.

![image](https://github.com/user-attachments/assets/847ec234-64e9-4d32-bcb4-679e2e81c1ad)

### ✅ What did you expect to see?

A HTML report with two attachments, given they're identical aside from one being a scenario and one being an example:

```gherkin
Feature: scenario
  Scenario: a scenario
    Given a step
```

```gherkin
Feature: example
  Example: an example
    Given a <type>

  Examples:
    | type |
    | step |
```

### 📦 Which tool/library version are you using?

node v18.20.4
cucumber-js v11.0.1

### 🔬 How could we reproduce it?

https://github.com/badeball/reproducible-issues/tree/master/cucumber/attach-in-examples

**Comment by mpkorstanje** [comment]
What happens when you click the blue `step` text in the report?

**Comment by badeball** [comment]
Oh, dang! I did not realize that that was a link! It takes me correctly to the example, in which the attachment is shown. Hence this can be closed.
