### ISSUE TITLE
Job URL missing?

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/react-components#50]
From @mpkorstanje here: https://github.com/cucumber/common/issues/1871#issuecomment-1025143224

> It doesn't break any more but, some information is still missing:
> 
> With this meta message:
> 
> ```
> {
>   "meta": {
>     "protocolVersion": "17.1.1",
>     "implementation": {
>       "name": "cucumber-jvm",
>       "version": "${parent.version}"
>     },
>     "runtime": {
>       "name": "OpenJDK 64-Bit Server VM",
>       "version": "15.0.2+7"
>     },
>     "os": {
>       "name": "Linux"
>     },
>     "cpu": {
>       "name": "amd64"
>     },
>     "ci": {
>       "name": "GitLab",
>       "url": "https://gitlab.com/gitlab-examples/ci-debug-trace/-/jobs/379424655",
>       "buildNumber": "12345"
>     }
>   }
> }
> ```
> 
> I would expect to see the url to the job.
> 
> ![image](https://user-images.githubusercontent.com/6946919/151701640-f7aed59a-21a2-4ab3-8f7d-8f4f13dab58b.png)

**Comment by ludeknovy** [comment]
I guess the `ci.url` was never displayed, at least it looks like from the current code. I added a test and it fails:

```
 it('should include the build link', () => {
      const { getByText } = render(<ExecutionSummary {...DEFAULT_PROPS} />)
      assert.ok(getByText(DEFAULT_PROPS.meta?.ci?.url as string))
    })
```

Story book does not includes the information either: /story/app-executionsummary--with-ci


I suggest adding a new `CIBuildLink` component in order to display this information.

**Comment by aurelien-reeves** [comment]
Indeed. That header, with those infos, is pretty new and copied from cucumber reports.

@ludeknovy  Would you agree to push your tests into a new PR?

**Comment by ludeknovy** [comment]
I see! 

Sure, currently trying to create that new component.

**Comment by aurelien-reeves** [comment]
Great, thank you :)

**Comment by ludeknovy** [comment]
![Screenshot 2022-04-19 at 10 02 33](https://user-images.githubusercontent.com/13610612/163955165-5082f94d-496c-4236-aa66-bab539f2fb96.png)

Is there any desired icon/look for this ?

**Comment by aurelien-reeves** [comment]
This is brand new, so I guess your proposition is fine 🤩

**Comment by mattwynne** [comment]
Thanks @ludeknovy!
