### ISSUE TITLE
Make ESM module

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/react-components#7]
I started working on this (declared type `module` in `package.json` and `tsconfig.json`). But I reverted to `commonjs` because there are other issues to fix first, like #6.

**Comment by aurelien-reeves** [comment]
In progress: #17 
Seems pretty difficult :(

**Comment by davidjgoss** [comment]
Unlike with most of our other JS packages, I don't think we need to make this a hybrid module. The consumers are browsers rather than Node.js programs, and all major bundlers and test runners now support ESM, so we should be able to just switch straight to ESM.
