### ISSUE TITLE
attach only works for first scenario in outline when using HTML formatter

### ISSUE THREAD

**Issue by rolengrays** [cucumber/react-components#79]
**Describe the bug**

When outputting HTML report with Scenario Template, `Scenario::attach` only works for the first scenario in a Scenario Outline.

**To Reproduce**

1. Create a test case as follows:

```gherkin
Feature: attach data to HTML report
  Scenario Template: test
    Then store '<val>'
  Examples:
    | val |
    | foo |
    | bar |
```

```java
package org.example;

import io.cucumber.java.After;
import io.cucumber.java.Scenario;
import io.cucumber.java.en.Then;

public class StepDefinitions {
  private String text;

  @Then("store {string}")
  public void store(String t) {
    this.text = t;
  }

  @After
  public void attach(Scenario s) {
    String line = s.getLine().toString();
    s.attach("val: " + this.text, "text/plain", line);
    System.out.println(this.text + " attached");
    this.text = "";
  }
}
```

```java
package org.example;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"html:target/report.html"})
public class RunCucumberTest {
}
```

2. Run `mvn test`
3. Both `foo attached` and `bar attached` are displayed on my console, but `target/report.html` only shows `val: foo`.

```txt
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Running org.example.RunCucumberTest
foo attached
bar attached

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.642 sec
...
```

**Expected behavior**

`target/report.html` shows both `val: foo` and `val: bar`.

**Context & Motivation**

For example, When some tests fails, we can get addtional information **for each test that has parameters** from HTML report. These are helpful for debugging.

**Screenshots**

![Cucumber - Google Chrome 2020_09_27 23_25_36](https://user-images.githubusercontent.com/28141853/94369470-ca55c080-0124-11eb-8946-935129cae8df.png)

**Environment**

 - Cucumber Version: 6.7.0
 - OS: Windows 10 1909
 - Runtime: OpenJDK 14.0.2
 - Build tool: Apache Maven 3.6.3
 - Browser: Google Chrome 85.0.4183.121

**Additional context**

It seems that `val: bar` is found in `window.CUCUMBER_MESSAGES` but not renderd.

```shell-session
$ grep -o -E "val:\s(foo|bar)" target/report.html
val: foo
val: bar
```

**Comment by EnoahNetzach** [comment]
Just joining to say that the attachments are not shown if there's only one scenario outline with one example

**Comment by ludeknovy** [comment]
@EnoahNetzach Interesting, for me it works if there is actually only one example. But once there are more of them, the attachments are gone :|

**Comment by davidjgoss** [comment]
So I think we may need to change approach here.

The test cases that scenario outlines fan out into can have wildly different:
- statuses (per step and overall)
- attachments

https://github.com/cucumber/cucumber-react/issues/75 adds another dimension of complexity because retries are on a per test case basis also.

I think we should consider displaying a scenario outline in the report with only the statuses indicated (worst status per step as per current logic) and then each example row should have an action to "drill down" i.e. open the full result for that exampe including the statuses, attachments (and possibly in future any previous attempts when retry is accounted for).

Thoughts?

**Comment by ludeknovy** [comment]
> each example row should have an action to "drill down" i.e. open the full result for that exampe including the statuses, attachments

This sounds very reasonable to me and how I would expect it to behave as an end-user.

**Comment by ludeknovy** [comment]
Is anyone planning to start working on it?

**Comment by davidjgoss** [comment]
I’ll take a look today!

**Comment by luke-hill** [comment]
FYI @davidjgoss from our discussions at the meetings. The worst case scenario *is* the best outcome IMO.

Where there are multiple instances, I would wager the *last* failure is probably the correct one for attach.

**Comment by davidjgoss** [comment]
@luke-hill sorry I don't understand that point. Are you talking about retries?

**Comment by luke-hill** [comment]
> I think we should consider displaying a scenario outline in the report with only the statuses indicated (worst status per step as per current logic) and then each example row should have an action to "drill down" i.e. open the full result for that exampe including the statuses, attachments (and possibly in future any previous attempts when retry is accounted for).

Yes I agree. I think that....
- When failing attach attaches the screenshot per scenario outline item
- If a single scenario outline is then retried multiple times, and fails each time. Maybe attach the last instance (As that is the "best" outcome)

**Comment by ypolancodgii** [comment]
What happened with that issue? Is there a solution that allows attaching a screen for each example?

**Comment by mpkorstanje** [comment]
It was resolved in 2022.  In the report, the examples are clickable and will take you to a detailed view for that example that includes attachments and logs.  Do make sure you are on a recent version of Cucumber.
